/*
 * Generates supabase/seed.sql from the current mock data (validated first).
 *
 *   npm run seed:sql
 *
 * Run AFTER applying migrations 0001 + 0002. Uses slug natural keys + subqueries
 * for foreign keys and ON CONFLICT DO NOTHING so it is safe to re-run.
 */
import { writeFileSync } from 'node:fs';

const store = new Map<string, string>();
(globalThis as unknown as { localStorage: Storage }).localStorage = {
  getItem: (k: string) => store.get(k) ?? null,
  setItem: (k: string, v: string) => void store.set(k, String(v)),
  removeItem: (k: string) => void store.delete(k),
  clear: () => store.clear(),
  key: () => null,
  length: 0,
} as Storage;

const { SUBSTANCES, BRANDS, STACKS, SOURCES, TYPE_TAGS, MARKERS, BEARINGS, DOMAIN_STRUCTURE } =
  await import('../src/data/mockData');
const { validateDataset } = await import('../src/services/seed/import');

const ADMIN_METHODS = ['👄 Oral', '💉 Injectable', '🧴 Topical', '👅 Sublingual'];

const q = (v: string | undefined | null) => (v == null ? 'null' : `'${v.replace(/'/g, "''")}'`);
const slug = (v: string) =>
  v
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
const subSub = (s: string) => `(select id from substances where slug='${s}')`;
const subBrand = (s: string) => `(select id from brands where slug='${s}')`;
const subStack = (sig: string) => `(select id from stacks where component_signature='${sig}')`;

// Validate before emitting.
const report = validateDataset({
  substances: SUBSTANCES.map((s) => ({
    slug: s.id,
    name: s.name,
    classification: s.classification,
    description: s.description,
    categoryRoutes: s.paths.map((p) => `${p.domain}:${p.category}`),
    typeTags: s.typeTags,
    administrationMethods: s.administration,
    markers: s.markers,
  })),
  brands: BRANDS.map((b) => ({ slug: b.id, name: b.name })),
  stacks: STACKS.map((s) => ({ name: s.name, description: s.description, componentSlugs: s.substances.map((c) => c.id) })),
  sources: [],
});
if (!report.ok) {
  console.error('Refusing to generate seed: dataset has validation issues.', report.issues);
  process.exit(1);
}

const lines: string[] = [];
lines.push('-- GENERATED by scripts/generate-seed-sql.ts — do not edit by hand.');
lines.push('-- Apply after migrations 0001 + 0002. Safe to re-run.');
lines.push('begin;');
lines.push('set constraints all deferred;');

// Controlled vocabularies.
lines.push('\n-- type_tags');
for (const t of TYPE_TAGS) {
  lines.push(
    `insert into type_tags (slug,label,emoji) values (${q(slug(t.label))},${q(t.label)},${q(t.emoji)}) on conflict (slug) do nothing;`,
  );
}
lines.push('\n-- administration_methods');
for (const a of ADMIN_METHODS) {
  lines.push(
    `insert into administration_methods (slug,label) values (${q(slug(a))},${q(a)}) on conflict (slug) do nothing;`,
  );
}
lines.push('\n-- markers');
for (const m of MARKERS) {
  lines.push(`insert into markers (slug,label) values (${q(slug(m))},${q(m)}) on conflict (slug) do nothing;`);
}
lines.push('\n-- bearings');
for (const b of BEARINGS) {
  lines.push(`insert into bearings (slug,label) values (${q(slug(b))},${q(b)}) on conflict (slug) do nothing;`);
}
lines.push('\n-- category_routes');
const routeSet = new Set<string>();
for (const d of DOMAIN_STRUCTURE) for (const c of d.categories) routeSet.add(`${d.domain}:${c.name}`);
for (const r of routeSet) {
  const [domain, category] = r.split(':');
  lines.push(
    `insert into category_routes (domain,category) values (${q(domain)},${q(category)}) on conflict (domain,category) do nothing;`,
  );
}

// Brands.
lines.push('\n-- brands');
for (const b of BRANDS) {
  lines.push(
    `insert into brands (slug,name,description,shipping_reliability,contamination_reports) values (${q(b.id)},${q(b.name)},${q(b.description)},${b.shippingReliability},${b.contaminationReports}) on conflict (slug) do nothing;`,
  );
}

// Substances.
lines.push('\n-- substances');
for (const s of SUBSTANCES) {
  lines.push(
    `insert into substances (slug,name,classification,description,average_dosage,length_of_cycle,tolerance_buildup,risk_level,formula) values (${q(s.id)},${q(s.name)},${q(s.classification)},${q(s.description)},${q(s.averageDosage)},${q(s.lengthOfCycle)},${q(s.toleranceBuildup)},${q(s.riskLevel)},${q(s.formula)}) on conflict (slug) do nothing;`,
  );
}
lines.push('\n-- substance.most_popular_brand');
for (const s of SUBSTANCES) {
  if (s.mostPopularBrandId)
    lines.push(`update substances set most_popular_brand_id=${subBrand(s.mostPopularBrandId)} where slug=${q(s.id)};`);
}

// Substance join tables.
lines.push('\n-- substance_routes / type_tags / administration / markers / effects');
for (const s of SUBSTANCES) {
  for (const p of s.paths)
    lines.push(
      `insert into substance_routes (substance_id,category_route_id) values (${subSub(s.id)},(select id from category_routes where domain=${q(p.domain)} and category=${q(p.category)})) on conflict do nothing;`,
    );
  for (const t of s.typeTags) {
    const label = TYPE_TAGS.find((x) => x.full === t)?.label ?? t;
    lines.push(
      `insert into substance_type_tags (substance_id,type_tag_id) values (${subSub(s.id)},(select id from type_tags where label=${q(label)})) on conflict do nothing;`,
    );
  }
  for (const a of s.administration)
    lines.push(
      `insert into substance_administration_methods (substance_id,administration_method_id) values (${subSub(s.id)},(select id from administration_methods where label=${q(a)})) on conflict do nothing;`,
    );
  for (const m of s.markers ?? [])
    lines.push(
      `insert into substance_markers (substance_id,marker_id) values (${subSub(s.id)},(select id from markers where label=${q(m)})) on conflict do nothing;`,
    );
  for (const e of s.subjectiveEffects)
    lines.push(`insert into substance_effects (substance_id,kind,value) values (${subSub(s.id)},'subjective_effect',${q(e)});`);
  for (const h of s.healthRisks)
    lines.push(`insert into substance_effects (substance_id,kind,value) values (${subSub(s.id)},'health_risk',${q(h)});`);
}

// Brand products + ingredients + health labels.
lines.push('\n-- brand products');
for (const b of BRANDS) {
  for (const p of b.productCatalog ?? []) {
    lines.push(
      `insert into brand_products (brand_id,substance_id,name) values (${subBrand(b.id)},${p.substanceId ? subSub(p.substanceId) : 'null'},${q(p.name)}) on conflict (brand_id,name) do nothing;`,
    );
    const prodRef = `(select id from brand_products where brand_id=${subBrand(b.id)} and name=${q(p.name)})`;
    for (const ing of p.ingredients ?? [])
      lines.push(
        `insert into brand_ingredients (brand_product_id,name,amount) values (${prodRef},${q(ing.name)},${q(ing.amount)});`,
      );
    for (const hl of p.healthLabels ?? [])
      lines.push(`insert into brand_health_labels (brand_product_id,label) values (${prodRef},${q(hl)});`);
  }
}

// Stacks + components.
lines.push('\n-- stacks');
const sig = (slugs: string[]) => slugs.map((x) => x.trim().toLowerCase()).sort().join('+');
for (const s of STACKS) {
  const signature = sig(s.substances.map((c) => c.id));
  lines.push(
    `insert into stacks (name,description,status,component_signature) values (${q(s.name)},${q(s.description)},${q(s.status)},${q(signature)}) on conflict (component_signature) do nothing;`,
  );
  for (const c of s.substances)
    lines.push(
      `insert into stack_components (stack_id,substance_id) values (${subStack(signature)},${subSub(c.id)}) on conflict do nothing;`,
    );
}

// Sources.
lines.push('\n-- sources');
const targetRef = (t: string, id: string) =>
  t === 'substance' ? subSub(id) : t === 'brand' ? subBrand(id) : subStack(sig(STACKS.find((s) => s.id === id)?.substances.map((c) => c.id) ?? []));
for (const src of SOURCES) {
  lines.push(
    `insert into sources (target_type,target_id,section,title,url,source_type,publisher,accessed_at) values (${q(src.targetType)},${targetRef(src.targetType, src.targetId)},${q(src.section)},${q(src.title)},${q(src.url)},${q(src.sourceType)},${q(src.publisher)},${src.accessedAt ? q(src.accessedAt) : 'null'});`,
  );
}

lines.push('\ncommit;');

writeFileSync('supabase/seed.sql', lines.join('\n') + '\n');
console.log(`Wrote supabase/seed.sql (${lines.length} statements).`);
